### ISSUE TITLE
Memory Leak - massive memory usage

### ISSUE THREAD

**Issue by krehberg** [karliuka/m2.SmartCategory#42]
Hello,

we have a large amount of products in the shop.
Currently it's round about 1,000,000 simple items, the most of them are related to 35,000 configurable items.
We configured around 590 category rules.

i just wanted to do a full reindex an discovered the following:

It takes 2 to 5 minutes per rule to complete the indexing.
It also stacks up the memory if there are conditions set. more complex conditions take more memory.
But the real problem is, that eventually all 128 GB RAM is used and the indexer gets "Killed".

I found out that it is related to the following function call:
class: vendor/faonni/module-smart-category/Model/Rule/Condition/Combine.php
function: collectValidatedAttributes($productCollection)

i tracked the memory usage around it and it keeps building up.

i failed freeing the memory in any possible way i could think of.

Could anybody please look into it and come up with some suggestions to fix this issue?

The "normal" indexing seems to work fine, because it never uses all the IDs to index, at least i hope so. But i'm not sure about the memory, because i got no time to track it, but i will next week.

Thanks in advance and best regards,
Kai

**Comment by joost-florijn-kega** [comment]
@krehberg 

I had the exact same problem and found the solution. Instead of fetch all the data at once i use a iterator (\Magento\Framework\Model\ResourceModel\IteratorFactory) to use all the attribute values. The function \Magento\Catalog\Model\ResourceModel\Product\Collection::getAllAttributeValues isn't designed to run multiple times during the same request. I will made a pull request for this module to fix this issue.
